Assets/Scenes/Bohan_LVL1_TEST.unity
Scene modified with some requests of Yuyue
=> Modified the scene

.gitattributes
config git lfs
I am not sure how the git lfs will update current resources
=> #19: Config .gitattribute to make use of git lfs

Assets/Resources/Prefabs/Player.prefab, Assets/Scenes/Bohan_LVL1_TEST.unity, Assets/Scripts/Player/PlayerCharacterControl.cs
=> #26 Refactor the wall walk

Assets/Resources/Prefabs/Player.prefab, Assets/Scenes/Bohan_LVL1_TEST.unity, Assets/Scripts/Player/PlayerCharacterControl.cs, UserSettings/EditorUserSettings.asset
=> #28 refactor the ledge climb

Assets/Resources/Prefabs/Player.prefab, Assets/Scripts/Player/PlayerCharacterControl.cs
=> #31 Improve the ledge climb by camera

Assets/Resources/Prefabs/PlayerController.prefab, Assets/Resources/Prefabs/UI/PanelDie.prefab, Assets/Resources/Prefabs/UI/PanelDie.prefab.meta, Assets/Resources/Prefabs/UI/TimeManager.prefab, Assets/Resources/Prefabs/UI/TimeManager.prefab.meta, Assets/Scenes/Dev/BohanXuM2.unity, Assets/Scenes/Dev/BohanXuM2.unity.meta, Assets/Scripts/Player/PlayerDeath.cs, Assets/Scripts/Player/TimeManager.cs, Assets/Scripts/Player/TimeManager.cs.meta, Assets/Scripts/UI/PanelDie.cs, Assets/Scripts/UI/PanelDie.cs.meta, Assets/Scripts/UI/TimeManagerUI.cs, Assets/Scripts/UI/TimeManagerUI.cs.meta
Add TimeManager UI prefab and its respective script. Remember to drag it into your own TestScene. 
Use TimeManager.instance to call AddTime and RemoveTime.
Added a PanelDie to spawn when play dies.
Register to Time. instance. TimeUpEffect for everything that needs to be done when time is up.
=> TimeManager Implementation.

Assets/Resources/Prefabs/Enemy/Bullet.prefab, Assets/Resources/Prefabs/Environments/MainMap.prefab, Assets/Resources/Prefabs/Level/Arrow.prefab, Assets/Resources/Prefabs/Level/Arrow.prefab.meta, Assets/Resources/Prefabs/PlayerController.prefab, Assets/Resources/Prefabs/UI/Canvas.prefab, Assets/Scenes/MainMap.unity, Deliverable/milestone-2/ITERATION.txt
=> feat(#50): Milestone 2 preparation

Assets/Animations/CameraAnimation.controller, Assets/Resources/Prefabs/PlayerController.prefab, Assets/Scenes/Dev/wumike dev main map.unity, Assets/Scenes/Dev/wumike dev main map.unity.meta, Assets/Scripts/Player/Move and Parkour/PlayerMoveControl.cs, Assets/Scripts/Player/Move and Parkour/PlayerParkour.cs, Assets/Scripts/Player/PlayerInputHandler.cs
jump distance according to holding
jumping forgiving after the player leaves the ground
TODO: we may need modifying some parameters. since there is a change in the implementation.
=> #56: improvement on jumping mechanic

Assets/Animations/CameraAnimation.controller, Assets/Resources/Prefabs/PlayerController.prefab, Assets/Scenes/Dev/wumike dev main map.unity, Assets/Scenes/Dev/wumike dev main map.unity.meta, Assets/Scripts/Player/Move and Parkour/PlayerParkour.cs, Assets/Scripts/Player/PlayerInputHandler.cs
=> #42: Improve and introduce wall running

Assets/Animations/CameraAnimation.controller, Assets/Resources/Prefabs/PlayerController.prefab, Assets/Scenes/Dev/wumike dev main map.unity, Assets/Scenes/Dev/wumike dev main map.unity.meta, Assets/Scripts/Player/Move and Parkour/PlayerMoveControl.cs, Assets/Scripts/Player/Move and Parkour/PlayerParkour.cs, Assets/Scripts/Player/PlayerInputHandler.cs
the player Moves slow when holding up and left
=> #57: Move slow when holding up and left

Assets/Scripts/Level/TimeManager.cs, UserSettings/EditorUserSettings.asset
This change now allows time to flow faster after a certain amount of "real time", preventing players from collecting bullets instead of moving forward. .
=> Gameplay Improvement: Time Manager

Assets/Resources/Prefabs/UI/Canvas.prefab, Assets/Scenes/MainMap.unity, Assets/Scripts/Player/Shield/PlayerShieldManager.cs
Updated docs at
https://github.com/UM-Electra-Studio/eecs494-p3/wiki/Shield-Mechanic
=> feat(#67): the shield uses a separate energy bar and add a new progress bar to display the energy

Assets/Resources/Prefabs/UI/ResetPanel.prefab, Assets/Scenes/Map1.unity
- include the issue id in jira, named the pull request with the feature, like `#1 set up the project management`
- one feature, one issue, one pull request
- do not forget to request view from other of us
=> level changes

Assets/Scenes/Dev/Map1 wumike.unity, Assets/Scripts/Player/Move and Parkour/PlayerParkour.cs
fix that the player cannot wall run after jumping off another wall
=> #73: follow on fix of wall run

Assets/Scripts/Player/Move and Parkour/PlayerParkour.cs, Assets/Scripts/Player/ObstructionDetection.cs
- when on the wall, only jump or leaving the wall will end wall run
- or the camera moves over 90 degree than the moving direction
=> feat(#80): new Wall run mechanic. only leaving the wall or jump or move the camera over than 90 degree of the running direction will end the wall run

Assets/Resources/Prefabs/PlayerController.prefab, Assets/Scenes/Dev/Map1 wumike.unity, Assets/Scenes/Map2.unity, Assets/Scripts/Player/Move and Parkour/PlayerMoveControl.cs, Assets/Scripts/Player/Move and Parkour/PlayerParkour.cs
=> feat(#75): head bobbing

Assets/Scripts/Player/PlayerInputHandler.cs, Assets/Scripts/UI/InGameOverlay.cs, Assets/Scripts/UI/TimeUpUI.cs
=> fix(#86): press esc will kill the game when death

Assets/Animations/Climb.anim, Assets/Resources/Prefabs/PlayerController.prefab, Assets/Scenes/Map1.unity
- fix that the camera will flash only for the first ledge climb
- adjust the climb time and the angle looking down
=> fix(#87): fix that the camera will flash only for the first ledge climb

Assets/Resources/Prefabs/PlayerController.prefab, Assets/Resources/Prefabs/UI/Canvas.prefab, Assets/Resources/Prefabs/UI/Time Manager UI.prefab, Assets/Scripts/Level/TimeManager.cs, Assets/Scripts/Player/CoinCollect/CoinCollect.cs, Assets/Scripts/Player/Move and Parkour/PlayerMoveControl.cs, Assets/Scripts/UI/TimeManagerUI.cs
- collect a coin will boost a fixed threshold and for a fixed time
- getting a new one during the boost will refresh the boost
- more intense head bobbing
=> #88: coin will boost speed

Assets/Resources/Prefabs/UI/Canvas.prefab, Assets/Resources/Prefabs/UI/Time Manager UI.prefab, Assets/Scripts/Level/TimeManager.cs, Assets/Scripts/UI/TimeManagerUI.cs
- include the issue id in jira, named the pull request with the feature, like `#1 set up the project management`
- one feature, one issue, one pull request
- do not forget to request view from other of us
=> #89: timer text UI, time change text UI and time manager mechanic change

Assets/Scripts/Player/Shield/ShieldControl.cs
- include the issue id in jira, named the pull request with the feature, like `#1 set up the project management`
- one feature, one issue, one pull request
- do not forget to request view from other of us
=> feat(#96): block bullet will no longer increase time

Assets/Audio/Effects/Jump1.wav, Assets/Audio/Effects/Jump2.wav, Assets/Audio/Effects/LevelComplete.wav, Assets/Audio/Effects/LevelComplete.wav.meta, Assets/Audio/Effects/LevelFailed.wav, Assets/Audio/Effects/LevelFailed.wav.meta, Assets/Resources/Prefabs/Level/LevelAudio.prefab, Assets/Resources/Prefabs/PlayerController.prefab, Assets/Scenes/Map1.unity, Assets/Scripts/AudioManager.cs, Assets/Scripts/AudioManager.cs.meta, Assets/Scripts/Level/TimeManager.cs, Assets/Scripts/Level/WinTrigger.cs, Assets/Scripts/Player/Move and Parkour/PlayerMoveControl.cs, Assets/Scripts/Player/Move and Parkour/PlayerParkour.cs, Assets/Scripts/UI/TimeUpUI.cs, UserSettings/EditorUserSettings.asset
- include the issue id in jira, named the pull request with the feature, like `#1 set up the project management`
- one feature, one issue, one pull request
- do not forget to request view from other of us
=> feat(*): modify on level 1 for GOLD
